#!/usr/bin/env python3
"""Generate the Detour launcher icon.

The mark is a road seen from above, curving across the frame with centre-line
dashes down it. Both ends of the centreline sit outside the 108x108 canvas, so
every launcher mask (circle, squircle, rounded square) crops the road into
something that carries on past the frame. That matters: an earlier perspective
version tapered to a rounded point and read as a tentacle rather than a road.
No visible end, no tentacle.

The road and its dashes are emitted as a single even-odd path, so the dashes
are holes. One silhouette therefore serves both the gradient foreground and the
tinted monochrome (themed icon) layer.

Run from anywhere; writes into the app/ and wear/ res directories:

    python3 tools/icon/gen_icon.py
"""

import math
import os

# Centreline of the road. First and last points are off-canvas by design.
CENTRELINE = [(22, 118), (22, 58), (86, 66), (86, -10)]
ROAD_WIDTH = 22.0
DASHES, DASH_FROM, DASH_TO = 6, 0.10, 0.90
DASH_LENGTH, DASH_WIDTH = 6.6, 5.5
SAMPLES = 80

AMBER_NEAR, AMBER_FAR = "#D2912C", "#F7E3B6"
BG_TOP, BG_BOTTOM = "#2E3524", "#0D1008"


def bezier(ctrl, t):
    pts = ctrl
    while len(pts) > 1:
        pts = [((1 - t) * a[0] + t * b[0], (1 - t) * a[1] + t * b[1])
               for a, b in zip(pts, pts[1:])]
    return pts[0]


def arc(cx, cy, r, a0, a1, seg):
    return [(cx + r * math.cos(a0 + (a1 - a0) * k / seg),
             cy + r * math.sin(a0 + (a1 - a0) * k / seg)) for k in range(seg + 1)]


def ring(points):
    return "M" + " L".join("%.2f,%.2f" % p for p in points) + " Z"


def road():
    """The road as a closed ring: the centreline offset to either side."""
    pts = [bezier(CENTRELINE, i / SAMPLES) for i in range(SAMPLES + 1)]
    left, right = [], []
    for i, (x, y) in enumerate(pts):
        a, b = pts[max(i - 1, 0)], pts[min(i + 1, SAMPLES)]
        dx, dy = b[0] - a[0], b[1] - a[1]
        length = math.hypot(dx, dy) or 1
        nx, ny = -dy / length, dx / length
        left.append((x + nx * ROAD_WIDTH / 2, y + ny * ROAD_WIDTH / 2))
        right.append((x - nx * ROAD_WIDTH / 2, y - ny * ROAD_WIDTH / 2))
    # No end caps: both ends are off-canvas and get cropped by the mask.
    return left + right[::-1]


def capsule(p1, p2, r, seg=8):
    dx, dy = p2[0] - p1[0], p2[1] - p1[1]
    length = math.hypot(dx, dy) or 1
    ux, uy = dx / length, dy / length
    nx, ny = -uy, ux
    heading = math.atan2(uy, ux)
    out = [(p1[0] + nx * r, p1[1] + ny * r), (p2[0] + nx * r, p2[1] + ny * r)]
    out += arc(p2[0], p2[1], r, heading + math.pi / 2, heading - math.pi / 2, seg)
    out += [(p1[0] - nx * r, p1[1] - ny * r)]
    out += arc(p1[0], p1[1], r, heading - math.pi / 2, heading - 3 * math.pi / 2, seg)
    return out


def dashes():
    out = []
    half = DASH_LENGTH / 2 / 100
    for k in range(DASHES):
        t = DASH_FROM + (DASH_TO - DASH_FROM) * k / (DASHES - 1)
        a = bezier(CENTRELINE, max(t - half, 0))
        b = bezier(CENTRELINE, min(t + half, 1))
        out.append(capsule(a, b, DASH_WIDTH / 2))
    return out


PATH = " ".join([ring(road())] + [ring(d) for d in dashes()])

HEAD = ('<?xml version="1.0" encoding="utf-8"?>\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    xmlns:aapt="http://schemas.android.com/aapt"\n'
        '    android:width="108dp"\n'
        '    android:height="108dp"\n'
        '    android:viewportWidth="108"\n'
        '    android:viewportHeight="108">\n')

GENERATED = ("    <!-- Generated by tools/icon/gen_icon.py - regenerate rather than\n"
             "         hand-editing this path. -->\n")


def gradient(x0, y0, x1, y1, c0, c1):
    return ('        <aapt:attr name="android:fillColor">\n'
            '            <gradient\n'
            '                android:type="linear"\n'
            '                android:startX="%s" android:startY="%s"\n'
            '                android:endX="%s" android:endY="%s">\n'
            '                <item android:offset="0" android:color="%s" />\n'
            '                <item android:offset="1" android:color="%s" />\n'
            '            </gradient>\n'
            '        </aapt:attr>\n' % (x0, y0, x1, y1, c0, c1))


FOREGROUND = (HEAD + GENERATED
              + '    <path\n        android:fillType="evenOdd"\n'
              + '        android:pathData="%s">\n' % PATH
              + gradient(24, 96, 84, 18, AMBER_NEAR, AMBER_FAR)
              + '    </path>\n</vector>\n')

BACKGROUND = (HEAD
              + '    <path android:pathData="M0,0h108v108h-108z">\n'
              + gradient(0, 0, 37.8, 108, BG_TOP, BG_BOTTOM)
              + '    </path>\n</vector>\n')

MONOCHROME = (HEAD + GENERATED
              + '    <!-- Themed-icon layer: same silhouette, tinted by the system. -->\n'
              + '    <path\n        android:fillType="evenOdd"\n'
              + '        android:fillColor="#FFFFFF"\n'
              + '        android:pathData="%s" />\n</vector>\n' % PATH)

ADAPTIVE = ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@drawable/ic_launcher_background" />\n'
            '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
            '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
            '</adaptive-icon>\n')


def main():
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    for module in ("app", "wear"):
        res = os.path.join(root, module, "src", "main", "res")
        for rel, body in (("drawable/ic_launcher_foreground.xml", FOREGROUND),
                          ("drawable/ic_launcher_background.xml", BACKGROUND),
                          ("drawable/ic_launcher_monochrome.xml", MONOCHROME),
                          ("mipmap-anydpi-v26/ic_launcher.xml", ADAPTIVE)):
            with open(os.path.join(res, rel), "w") as fh:
                fh.write(body)
        print("wrote %s icons" % module)


if __name__ == "__main__":
    main()
